### ISSUE TITLE
Incorrect phrasing of data source loading message

### ISSUE THREAD

**Issue by pont-us** [CCI-Tools/cate-app#144]
Currently, the data source loading message reads:

 - Please wait until the list of data sources is being loaded from the server.

This implies that the user should wait until the list *starts* being loaded rather than until it *finishes* being loaded. I suggest changing it to one of the following:

 - Please wait: the list of data sources is being loaded from the server.
 - Please wait while the list of data sources is loaded from the server.
 - Please wait until the list of data sources has been loaded from the server.

**Comment by pont-us** [comment]
Oops, opened this in the wrong repository -- closing.

**Comment by forman** [comment]
Fixed in 3.1.1 (in dev)
